// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: assetsToTags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAssetsToTags = `-- name: CreateAssetsToTags :one
INSERT INTO "assetsToTags" ("tagsId", "assetsId")
VALUES ($1, $2)
RETURNING "assetsId", "tagsId", "createdAt", "updatedAt"
`

type CreateAssetsToTagsParams struct {
	TagsId   uuid.UUID `json:"tagsId"`
	AssetsId uuid.UUID `json:"assetsId"`
}

func (q *Queries) CreateAssetsToTags(ctx context.Context, arg CreateAssetsToTagsParams) (AssetsToTags, error) {
	row := q.db.QueryRowContext(ctx, createAssetsToTags, arg.TagsId, arg.AssetsId)
	var i AssetsToTags
	err := row.Scan(
		&i.AssetsId,
		&i.TagsId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
