// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assets struct {
	ID            uuid.UUID      `json:"id"`
	Uid           uuid.NullUUID  `json:"uid"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	AssetUrl      string         `json:"assetUrl"`
	AssetType     string         `json:"assetType"`
	ThumbnailUrl  string         `json:"thumbnailUrl"`
	GaussianUrl   sql.NullString `json:"gaussianUrl"`
	PointCloudUrl sql.NullString `json:"pointCloudUrl"`
	IsPrivate     bool           `json:"isPrivate"`
	Likes         int32          `json:"likes"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

type AssetsToTags struct {
	AssetsId  uuid.UUID `json:"assetsId"`
	TagsId    uuid.UUID `json:"tagsId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Likes struct {
	ID        uuid.UUID     `json:"id"`
	Uid       uuid.NullUUID `json:"uid"`
	AssetsId  uuid.NullUUID `json:"assetsId"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type Tags struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Tasks struct {
	ID        uuid.UUID     `json:"id"`
	Uid       uuid.NullUUID `json:"uid"`
	Title     string        `json:"title"`
	Status    string        `json:"status"`
	Url       string        `json:"url"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type Users struct {
	Uid               uuid.UUID      `json:"uid"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Avatar            sql.NullString `json:"avatar"`
	Password          sql.NullString `json:"password"`
	Provider          string         `json:"provider"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         time.Time      `json:"updatedAt"`
	PasswordChangedAt time.Time      `json:"passwordChangedAt"`
}
