// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID               uuid.UUID      `json:"id"`
	Username         string         `json:"username"`
	Email            string         `json:"email"`
	Password         string         `json:"password"`
	PhoneNumber      sql.NullString `json:"phone_number"`
	FullName         sql.NullString `json:"full_name"`
	Avatar           sql.NullString `json:"avatar"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	PasswordChangeAt time.Time      `json:"password_change_at"`
}
