// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assets struct {
	ID                   uuid.UUID      `json:"id"`
	Uid                  uuid.UUID      `json:"uid"`
	Title                string         `json:"title"`
	Slug                 string         `json:"slug"`
	Type                 string         `json:"type"`
	ThumbnailUrl         string         `json:"thumbnailUrl"`
	PhotoDirUrl          string         `json:"photoDirUrl"`
	SplatUrl             sql.NullString `json:"splatUrl"`
	PclUrl               sql.NullString `json:"pclUrl"`
	PclColmapUrl         sql.NullString `json:"pclColmapUrl"`
	SegmentedPclDirUrl   sql.NullString `json:"segmentedPclDirUrl"`
	SegmentedSplatDirUrl sql.NullString `json:"segmentedSplatDirUrl"`
	IsPrivate            bool           `json:"isPrivate"`
	Status               string         `json:"status"`
	Likes                int32          `json:"likes"`
	CreatedAt            time.Time      `json:"createdAt"`
	UpdatedAt            time.Time      `json:"updatedAt"`
}

type AssetsToTags struct {
	AssetsId  uuid.UUID `json:"assetsId"`
	TagsId    uuid.UUID `json:"tagsId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Likes struct {
	Uid       uuid.UUID `json:"uid"`
	AssetsId  uuid.UUID `json:"assetsId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Tags struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Users struct {
	Uid               uuid.UUID      `json:"uid"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Avatar            sql.NullString `json:"avatar"`
	Password          sql.NullString `json:"password"`
	Provider          string         `json:"provider"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         time.Time      `json:"updatedAt"`
	PasswordChangedAt time.Time      `json:"passwordChangedAt"`
}
