// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CheckIsLiked(ctx context.Context, arg CheckIsLikedParams) (bool, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Assets, error)
	CreateAssetsToTags(ctx context.Context, arg CreateAssetsToTagsParams) (AssetsToTags, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) (Tags, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DecreaseAssetLikes(ctx context.Context, id uuid.UUID) (Assets, error)
	GetAllAssets(ctx context.Context) ([]GetAllAssetsRow, error)
	GetAllAssetsByKeyword(ctx context.Context, dollar_1 sql.NullString) ([]GetAllAssetsByKeywordRow, error)
	GetAllAssetsWithLikesInformation(ctx context.Context, arg GetAllAssetsWithLikesInformationParams) ([]GetAllAssetsWithLikesInformationRow, error)
	GetAssetsById(ctx context.Context, id uuid.UUID) (Assets, error)
	GetAssetsBySlug(ctx context.Context, slug string) (Assets, error)
	GetAssetsByUid(ctx context.Context, uid uuid.UUID) ([]Assets, error)
	GetMyAssets(ctx context.Context, arg GetMyAssetsParams) ([]GetMyAssetsRow, error)
	GetSlug(ctx context.Context, slug string) ([]string, error)
	GetTagsByKeyword(ctx context.Context, arg GetTagsByKeywordParams) ([]Tags, error)
	GetTagsByTagsName(ctx context.Context, name []string) ([]Tags, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserById(ctx context.Context, uid uuid.UUID) (Users, error)
	IncreaseAssetLikes(ctx context.Context, id uuid.UUID) (Assets, error)
	RemoveAsset(ctx context.Context, arg RemoveAssetParams) (Assets, error)
	RemoveLike(ctx context.Context, arg RemoveLikeParams) (Likes, error)
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Assets, error)
	UpdateAssetUrl(ctx context.Context, arg UpdateAssetUrlParams) (Assets, error)
	UpdateGaussianUrl(ctx context.Context, arg UpdateGaussianUrlParams) (Assets, error)
	UpdatePointCloudUrl(ctx context.Context, arg UpdatePointCloudUrlParams) (Assets, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
